name: Build and Deploy to AKS

on:
  push:
    branches: [ "main" ] # Déclenche le workflow à chaque push sur main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}
        # GitHub Actions tourne sur du x86_64, donc le build sera nativement compatible AMD64 !
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/my-api:${{ github.sha }} .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-api:${{ github.sha }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.CLUSTER_NAME }}

    - name: Deploy to AKS
      run: |
        # On utilise sed pour mettre à jour l'image avec le tag du commit actuel dans le YAML
        sed -i "s|image:.*|image: ${{ secrets.ACR_NAME }}.azurecr.io/my-api:${{ github.sha }}|g" k8s/deployment.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml